USE [master]
GO

/****** Object:  Database [BroPhone]    Script Date: 03/11/2022 18:01:45 ******/
CREATE DATABASE [BroPhone]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BroPhone', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BroPhone.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BroPhone_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BroPhone_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BroPhone].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BroPhone] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BroPhone] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BroPhone] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BroPhone] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BroPhone] SET ARITHABORT OFF 
GO

ALTER DATABASE [BroPhone] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BroPhone] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BroPhone] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BroPhone] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BroPhone] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BroPhone] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BroPhone] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BroPhone] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BroPhone] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BroPhone] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BroPhone] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BroPhone] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BroPhone] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BroPhone] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BroPhone] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BroPhone] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BroPhone] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BroPhone] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BroPhone] SET  MULTI_USER 
GO

ALTER DATABASE [BroPhone] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BroPhone] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BroPhone] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BroPhone] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BroPhone] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BroPhone] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BroPhone] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BroPhone] SET  READ_WRITE 
GO

